site_name: Oedometer Docs
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [".."]   # <- wichtig: findet ../classes
          options:
            docstring_style: google
            docstring_section_style: table     # hübsche Tabellen für Args/Returns
            members_order: source              # wie im Code
            show_source: false
            show_signature: true
            separate_signature: true
            filters: ["!^_"]                   # private Methoden ausblenden

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - ../classes
